{% set name = "badger-opt" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/badger-opt-{{ version }}.tar.gz
  sha256: 7a12849df5aaecd6bf52eee67f977e80ad82135ce5a2f5fb7ff700e5fa4344a4

build:
  number: 0
  noarch: python
  entry_points:
    - badger = badger.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - pip
    - python >=3.6
    - xorg-libxfixes  # [linux]
  run:
    - coolname
    - pandas
    - pillow
    - pyqt
    - pyqtgraph
    - python >=3.6
    - pyyaml
    - qdarkstyle

test:
  imports:
    - badger
  files:
    - tests
  commands:
    - pip check
    - badger --help
    - pytest tests
  requires:
    - pip
    - pytest
    - pytest-qt

about:
  home: https://github.com/SLAC-ML/Badger
  summary: Core of the Badger optimizer
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wenatuhs
